services:
  - type: web
    name: workflowguard-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: HUBSPOT_CLIENT_ID
        sync: false
      - key: HUBSPOT_CLIENT_SECRET
        sync: false
      - key: HUBSPOT_REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false 